// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wacqcbsdqblzrymsfazx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhY3FjYnNkcWJsenJ5bXNmYXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMjc2MTYsImV4cCI6MjA3NzYwMzYxNn0.9rUNu2nNH8257O-_yFiVPfdFX52nW6qQnQA9jg2Vxj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});